// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/rigelrozanski/thranch/quac/idea
package quac

import (
	"github.com/rigelrozanski/thranch/quac/idea"
)

const (
	Last          = idea.Last
	CycleAlive    = idea.CycleAlive
	CycleConsumed = idea.CycleConsumed
	CycleZombie   = idea.CycleZombie
	KindText      = idea.KindText
	KindImage     = idea.KindImage
	KindAudio     = idea.KindAudio
	KindEnText    = idea.KindEnText
)

var (
	// functions aliases
	GetIdByFilename          = idea.GetIdByFilename
	GetNextID                = idea.GetNextID
	IncrementID              = idea.IncrementID
	ParseID                  = idea.ParseID
	ParseIDNoLogLast         = idea.ParseIDNoLogLast
	ParseIDOp                = idea.ParseIDOp
	PrependLast              = idea.PrependLast
	GetLastIDs               = idea.GetLastIDs
	NewNonConsumingTextIdea  = idea.NewNonConsumingTextIdea
	NewTextIdea              = idea.NewTextIdea
	NewIdeaFromFile          = idea.NewIdeaFromFile
	NewConsumingTextIdea     = idea.NewConsumingTextIdea
	NewIdeaFromFilepath      = idea.NewIdeaFromFilepath
	NewIdeaFromFilename      = idea.NewIdeaFromFilename
	GetAllIdeasNonConsuming  = idea.GetAllIdeasNonConsuming
	GetAllIdeas              = idea.GetAllIdeas
	GetAllIdeasInRange       = idea.GetAllIdeasInRange
	ConcatAllContentFromTags = idea.ConcatAllContentFromTags
	TodayDate                = idea.TodayDate
	GetKind                  = idea.GetKind
	IdStr                    = idea.IdStr

	// variable aliases
	IdeasDir   = idea.IdeasDir
	ConfigFile = idea.ConfigFile
	LastIdFile = idea.LastIdFile
)

type (
	Idea  = idea.Idea
	Ideas = idea.Ideas
)
